import { Router } from 'express';

import * as audit from '../lib/audit.js';
import { createToken, deleteToken, listTokens } from '../lib/api-tokens.js';
import { ValidationError } from '../lib/errors.js';
import * as logger from '../lib/logger.js';

import { requireAdmin } from '../middleware/auth.js';

// /api/api-tokens — admin-only CRUD for programmatic-access tokens.
//
// The wire format `pp_<keyId>.<secret>` is generated by lib/api-tokens.js
// and only returned by POST. Subsequent GETs expose keyId + name + dates
// only — the secret can never be retrieved again (bcrypt-hashed at rest,
// no reversible encryption like Armor's optional encrypted_full_key).
//
// Usage in scripts:
//   curl -H "Authorization: Bearer pp_xxxxxxxx.<32-hex>" \
//        https://patchpanel.local:8099/api/state

export const apiTokensRouter = config => {
  const router = Router();

  router.use(requireAdmin);

  // GET /api/api-tokens — list (no secrets).
  router.get('/api-tokens', async (req, res, next) => {
    logger.debug('GET /api-tokens', { actor: req.user?.id });
    try {
      const tokens = await listTokens(config.paths.apiTokens);
      res.json({ tokens });
    } catch (err) {
      next(err);
    }
  });

  // POST /api/api-tokens — mint a new token. Body: { name, expiresAt?: ISO }.
  // Response includes `wire`: the only time the secret is ever returned.
  router.post('/api-tokens', async (req, res, next) => {
    try {
      const { name, expiresAt } = req.body ?? {};
      if (typeof name !== 'string') {
        throw new ValidationError('name is required');
      }
      const { token, wire } = await createToken(
        config.paths.apiTokens,
        { name, createdBy: req.user.id, expiresAt: expiresAt ?? null },
        { bcryptRounds: config.security?.bcryptRounds ?? 12 }
      );
      audit.record({
        actor: req.user.id,
        category: 'api-token',
        action: 'create',
        target: token.keyId,
        outcome: 'ok',
        details: { name: token.name, expiresAt: token.expiresAt },
      });
      res.status(201).json({ token, wire });
    } catch (err) {
      next(err);
    }
  });

  // DELETE /api/api-tokens/:keyId — revoke.
  router.delete('/api-tokens/:keyId', async (req, res, next) => {
    const { keyId } = req.params;
    try {
      await deleteToken(config.paths.apiTokens, keyId);
      audit.record({
        actor: req.user.id,
        category: 'api-token',
        action: 'delete',
        target: keyId,
        outcome: 'ok',
      });
      res.json({ ok: true });
    } catch (err) {
      next(err);
    }
  });

  return router;
};
